name: Desplegar Sitio Web en Hosting # Nombre de la automatización que verás en GitHub

on:
  push:
    branches:
      - main # Se ejecutará cada vez que hagas 'push' específicamente a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest # Usa una máquina virtual de Ubuntu para ejecutar los pasos
    steps:
      - name: Checkout del código # Paso 1: Descarga el código de tu repositorio a la máquina virtual
        uses: actions/checkout@v4

      - name: Despliegue con FTP # Paso 2: Usa una herramienta pre-hecha para subir los archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }} # Usa el Secreto que creaste para el servidor
          username: ${{ secrets.FTP_USERNAME }} # Usa el Secreto que creaste para el usuario
          password: ${{ secrets.FTP_PASSWORD }} # Usa el Secreto que creaste para la contraseña
          # ¡IMPORTANTE! La ruta completa y CORRECTA donde quieres que se suban los archivos.
          # Asegúrate de que la carpeta 'cifrado' exista en tu hosting.
          server-dir: '/cifrado/'